/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Javascript',
      items: [
        'Javascript/bian-liang-ti-sheng',
        'Javascript/js-type',
        'Javascript/shuang-deng',
        'Javascript/han-shu-shi-bian-cheng',
        'Javascript/this',
        'Javascript/ci-fa-zuo-yong-yu-ji-zuo-yong-yu-lian',
        'Javascript/bi-bao',
        'Javascript/shi-jian-ji-zhi',
        'Javascript/Promise',
        'Javascript/debounce-throttle',
        'Javascript/ji-cheng-yu-yuan-xing',
      ],
    },
    {
      type: 'category',
      label: 'HTML',
      items: ['HTML/index', 'HTML/yu-yi-hua', 'HTML/head', 'HTML/element', 'HTML/css'],
    },
    {
      type: 'category',
      label: 'CSS',
      items: ['CSS/index', 'CSS/create-css', 'CSS/position', 'CSS/css-bu-ju', 'CSS/css-bai-fen-bi','CSS/SassVsLess'],
    },
    {
      type: 'category',
      label: 'Browser',
      items: ['Browser/network connect'],
    },
    {
      type: 'category',
      label: '工程化',
      items: ['Engineering/intro', 'Engineering/Module'],
    },
    {
      type: 'category',
      label: 'Yarn',
      items: ['Yarn/ErrorHelp'],
    },
  ],
};

module.exports = sidebars;
